platform :ios, '15.0'

target 'PodTests' do
  use_frameworks!

  # pod 'libsmb2', :path => 'Submodules/libsmb2'
  # pod 'AMSMB2', :path => 'Submodules/AMSMB2'
  
  pod 'libsmb2', :git => 'git@github.com:everappz/libsmb2.git'
  pod 'AMSMB2', :git => 'git@github.com:everappz/AMSMB2.git'
end
